# dataset
train_dir: "/data/zhangyangyang/leaves_prediction/data/train/"
test_dir: "/data/zhangyangyang/leaves_prediction/data/test/"
ratio: 0.8
picture_size: 224

# model
seed: 8
batch_size: 256
num_workers: 8
start_epoch: 50
epochs: 100

# network
resnet_type: 'myResNet'  # myResNet(2)/ResNet18/ResNet34/ResNet50(1)
model_path: "./model_save/"
model_name: "version0.2"   # version1, etc
# Adam

# train_figure
reload: False
weight_decay: 0.0001
learning_rate: 1e-3
grad_clip: 0.1

# plt
plt_path: "/data/zhangyangyang/leaves_prediction/plt_save/"