# dataset
train_dir: "/data/zhangyangyang/leaves_prediction/data/train/"
test_dir: "/data/zhangyangyang/leaves_prediction/data/test/"
ratio: 0.9
picture_size: 256

# model
seed: 8
batch_size: 256
num_workers: 4
start_epoch: 0
epochs: 20

# network
resnet_type: 'myResNet'  # myResNet(2)/ResNet18/ResNet34/ResNet50(1)
model_path: "./model_save/"
model_name: "version0.3"   # version1, etc

# train_figure
reload: False
weight_decay: 0.0001
learning_rate: 0.001
grad_clip: 0.1

# plt
plt_path: "/data/zhangyangyang/leaves_prediction/plt_save/"