# dataset
train_dir: "./train/"
test_dir: "./test/"
ratio: 0.8
picture_size: 224

# model
seed: 8
batch_size: 256
num_workers: 8
start_epoch: 50
epochs: 100

# network
resnet_type: 'myResNet'  # myResNet(2)/ResNet18/ResNet34/ResNet50(1)
model_path: "./model_save/"
model_name: "version0.1"   # version1, etc

# train_figure
reload: False
weight_decay: 0.0001
learning_rate: 0.001
grad_clip: 0.1

# plt
plt_path: "./plt_save/"